[package]
name = "c64"
version = "0.1.0"
authors = ["Rink Springer <rink@rink.nu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "c64-emu"

[dependencies]
sdl2 = "0.32.2"
